# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       harbour-fotokopierer

# >> macros
# << macros

Summary:    Document Scanner
Version:    0.1
Release:    1
Group:      Qt/Qt
License:    GPLv3+
URL:        https://fifr.spdns.de/fossils/harbour-fotokopierer
Source0:    %{name}-%{version}.tar.bz2
Source100:  harbour-fotokopierer.yaml
Requires:   sailfishsilica-qt5 >= 0.10.9
BuildRequires:  pkgconfig(sailfishapp) >= 1.0.2
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Gui)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(openssl)
BuildRequires:  pkgconfig(libpng16)
BuildRequires:  pkgconfig(zlib)
BuildRequires:  cmake
BuildRequires:  desktop-file-utils

%description
This sample project shows how to build a Sailfish application with a
custom build system.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
rm -rf rpmbuilddir
mkdir rpmbuilddir
cd rpmbuilddir &&  cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=/usr ..
cd ..
make -C rpmbuilddir -j VERBOSE=1 %{?_smp_mflags}
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
DESTDIR=%{buildroot} make -C rpmbuilddir install
mkdir -p %{_bindir}
# << install pre

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_bindir}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/86x86/apps/%{name}.png
# >> files
# << files
