# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       harbour-fotokopierer

# >> macros
# << macros

Summary:    Document Scanner
Version:    0.2.4
Release:    1%{?dist}
Group:      Qt/Qt
License:    GPLv3+
URL:        https://fifr.spdns.de/fossils/harbour-fotokopierer
Source0:    %{name}-%{version}.tar.bz2
Source100:  harbour-fotokopierer.yaml
Requires:   sailfishsilica-qt5 >= 0.10.9
BuildRequires:  pkgconfig(sailfishapp) >= 1.0.2
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Concurrent)
BuildRequires:  pkgconfig(Qt5Gui)
BuildRequires:  pkgconfig(Qt5Multimedia)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(openssl)
BuildRequires:  pkgconfig(libpng16)
BuildRequires:  pkgconfig(zlib)
BuildRequires:  cmake
BuildRequires:  qt5-qtmultimedia-plugin-audio-alsa
BuildRequires:  qt5-qtmultimedia-plugin-audio-pulseaudio
BuildRequires:  qt5-qtmultimedia-plugin-mediaservice-gstaudiodecoder
BuildRequires:  qt5-qtmultimedia-plugin-mediaservice-gstcamerabin
BuildRequires:  qt5-qtmultimedia-plugin-mediaservice-gstmediacapture
BuildRequires:  qt5-qtmultimedia-plugin-mediaservice-gstmediaplayer
BuildRequires:  qt5-qtmultimedia-plugin-mediaservice-irisradio
BuildRequires:  qt5-qtmultimedia-plugin-mediaservice-irisradio
BuildRequires:  qt5-qtmultimedia-plugin-playlistformats-m3u
BuildRequires:  qt5-qtmultimedia-plugin-resourcepolicy-resourceqt
BuildRequires:  qt5-qtmultimedia-plugin-video-eglvideonode
BuildRequires:  desktop-file-utils

%description
This sample project shows how to build a Sailfish application with a
custom build system.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
rm -rf rpmbuilddir-%{_arch}
mkdir rpmbuilddir-%{_arch}
pushd rpmbuilddir-%{_arch} &&  cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=/usr %{_sourcedir}/..
popd
make -C rpmbuilddir-%{_arch} VERBOSE=1 %{?_smp_mflags}
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
DESTDIR=%{buildroot} make -C rpmbuilddir-%{_arch} install
mkdir -p %{_bindir}
# << install pre

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_bindir}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/*/apps/%{name}.png
# >> files
# << files
