# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       harbour-fotokopierer

# >> macros
# << macros

Summary:    Document Scanner
Version:    0.4.8
Release:    1%{?dist}
Group:      Qt/Qt
License:    GPLv3+
URL:        https://chiselapp.com/user/fifr/repository/fotokopierer
Source0:    %{name}-%{version}.tar.gz
Source1:    %{opencv_version}.zip
Source2:    podofo-%{podofo_version}.tar.gz
Source3:    freetype-%{freetype_version}.tar.gz
Source100:  harbour-fotokopierer.yaml
Requires:   sailfishsilica-qt5 >= 0.10.9
BuildRequires:  pkgconfig(sailfishapp) >= 1.0.2
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Concurrent)
BuildRequires:  pkgconfig(Qt5Gui)
BuildRequires:  pkgconfig(Qt5Multimedia)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(openssl) >= 1.1
BuildRequires:  pkgconfig(libpng16)
BuildRequires:  pkgconfig(zlib)
BuildRequires:  cmake
BuildRequires:  qt5-qtmultimedia-plugin-audio-alsa
BuildRequires:  qt5-qtmultimedia-plugin-audio-pulseaudio
BuildRequires:  qt5-qtmultimedia-plugin-mediaservice-gstaudiodecoder
BuildRequires:  qt5-qtmultimedia-plugin-mediaservice-gstcamerabin
BuildRequires:  qt5-qtmultimedia-plugin-mediaservice-gstmediacapture
BuildRequires:  qt5-qtmultimedia-plugin-mediaservice-gstmediaplayer
BuildRequires:  qt5-qtmultimedia-plugin-mediaservice-irisradio
BuildRequires:  qt5-qtmultimedia-plugin-mediaservice-irisradio
BuildRequires:  qt5-qtmultimedia-plugin-playlistformats-m3u
BuildRequires:  qt5-qtmultimedia-plugin-resourcepolicy-resourceqt
BuildRequires:  qt5-qtmultimedia-plugin-video-eglvideonode
BuildRequires:  desktop-file-utils

%description
A camera-scanning application for Sailfish OS.

PackageName: Fotokopierer
Type: desktop-application
DeveloperName: Frank Fischer
Categories:
  - Graphics
  - Office
Custom:
  Repo: https://chiselapp.com/user/fifr/repository/fotokopierer
  Icon: https://chiselapp.com/user/fifr/repository/fotokopierer/doc/release/icons/harbour-fotokopierer.svg
Screenshots:
  - https://chiselapp.com/user/fifr/repository/fotokopierer/uv/screenshot1.png
  - https://chiselapp.com/user/fifr/repository/fotokopierer/uv/screenshot2.png
  - https://chiselapp.com/user/fifr/repository/fotokopierer/uv/screenshot3.png
  - https://chiselapp.com/user/fifr/repository/fotokopierer/uv/screenshot4.png
PackageIcon: https://chiselapp.com/user/fifr/repository/fotokopierer/uv/harbour-fotokopierer.svg
Url:
  Homepage: https://chiselapp.com/user/fifr/repository/fotokopierer
  Help: https://chiselapp.com/user/fifr/repository/fotokopierer/forum
  Bugtracker: https://chiselapp.com/user/fifr/repository/fotokopierer/ticket


# >> macros2
%global opencv_version 3.4.16
%global podofo_version 0.9.8
%global freetype_version 2.13.2
# << macros2

%prep
# No setup

# >> setup
%setup -n %{name}-%{version}
mkdir -p 3rdparty
pushd 3rdparty
test -d opencv-%{opencv_version} || unzip %{SOURCE1}
test -d podofo-%{podofo_version} || tar -xzf %{SOURCE2}
test -d freetype-%{freetype_version} || tar -xzf %{SOURCE3}
popd
# << setup

%build
# >> build pre
mkdir -p rpmbuilddir-%{_arch}
pushd rpmbuilddir-%{_arch}

mkdir -p 3rdparty/opencv
pushd 3rdparty/opencv
if ! test -f Makefile; then
cmake ../../../3rdparty/opencv-%{opencv_version} \
-DCMAKE_INSTALL_PREFIX:PATH=$PWD/../../usr \
-DCMAKE_BUILD_TYPE=Release \
-DOPENCV_EXTRA_CXX_FLAGS="-U__SSE2__" \
-DBUILD_DOCS=OFF \
-DBUILD_EXAMPLES=OFF \
-DBUILD_FAT_JAVA_LIB=OFF \
-DBUILD_ITT=OFF \
-DBUILD_JAVA=OFF \
-DBUILD_PACKAGE=OFF \
-DBUILD_PERF_TESTS=OFF \
-DBUILD_SHARED_LIBS=OFF \
-DBUILD_TESTS=OFF \
-DBUILD_PROTOBUF=On \
-DBUILD_TIFF=OFF \
-DBUILD_JPEG=OFF \
-DBUILD_JPEG_TURBO_DISABLE=ON \
-DBUILD_opencv_apps=OFF \
-DBUILD_opencv_calib3d=OFF \
-DBUILD_opencv_dnn=OFF \
-DBUILD_opencv_features2d=OFF \
-DBUILD_opencv_flann=OFF \
-DBUILD_opencv_highgui=OFF \
-DBUILD_opencv_imgcodecs=OFF \
-DBUILD_opencv_ml=OFF \
-DBUILD_opencv_objdetect=OFF \
-DBUILD_opencv_photo=OFF \
-DBUILD_opencv_python2=OFF \
-DBUILD_opencv_python_bindings_generator=OFF \
-DBUILD_opencv_shape=OFF \
-DBUILD_opencv_stitching=OFF \
-DBUILD_opencv_superres=OFF \
-DBUILD_opencv_ts=OFF \
-DBUILD_opencv_video=OFF \
-DBUILD_opencv_videoio=OFF \
-DBUILD_opencv_videostab=OFF \
-DBUILD_opencv_world=OFF \
-DENABLE_PRECOMPILED_HEADERS=OFF \
-DWITH_JASPER=OFF \
-DWITH_OPENEXR=OFF \
-DWITH_WEBP=OFF
fi
make %{?_smp_mflags}
make libjpeg libtiff %{?_smp_mflags}
make install
popd

mkdir -p 3rdparty/freetype
pushd 3rdparty/freetype
if ! test -f Makefile; then
cmake ../../../3rdparty/freetype-%{freetype_version} \
-DCMAKE_INSTALL_PREFIX:PATH=$PWD/../../usr \
-DCMAKE_BUILD_TYPE=Release \
-DBUILD_SHARED_LIBS:BOOL=false \
-DCMAKE_POSITION_INDEPENDENT_CODE:BOOL=true
fi
make %{?_smp_mflags}
make install
popd

mkdir -p 3rdparty/podofo
pushd 3rdparty/podofo
if ! test -f Makefile; then
cmake ../../../3rdparty/podofo-%{podofo_version} \
-DCMAKE_INSTALL_PREFIX:PATH=$PWD/../../usr \
-DPODOFO_BUILD_LIB_ONLY:BOOL=true \
-DCMAKE_BUILD_TYPE=Release \
-DCMAKE_POSITION_INDEPENDENT_CODE:BOOL=true \
-DCMAKE_INCLUDE_PATH="$PWD/../../../3rdparty/opencv-%{opencv_version}/3rdparty/libjpeg;$PWD/../../../3rdparty/opencv-%{opencv_version}/3rdparty/libtiff;$PWD/../../usr/include/freetype" \
-DCMAKE_LIBRARY_PATH="$PWD/../../usr/lib;$PWD/../../3rdparty/opencv/3rdparty/lib" \
-DCMAKE_CXX_FLAGS="-isystem $PWD/../../3rdparty/opencv/3rdparty/libtiff" \
-DLIBJPEG_LIBRARY_NAMES="jpeg,libjpeg"
fi
make %{?_smp_mflags}
make install
popd

%cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo \
-DCMAKE_PREFIX_PATH="$PWD/3rdparty/opencv;$PWD/usr" \
-DCMAKE_INCLUDE_PATH="$PWD/../3rdparty/opencv-%{opencv_version}/3rdparty/libjpeg;$PWD/../3rdparty/opencv-%{opencv_version}/3rdparty/libtiff;$PWD/usr/include" \
-DCMAKE_LIBRARY_PATH="$PWD/usr/lib;$PWD/3rdparty/opencv/3rdparty/lib" \
-DCMAKE_INSTALL_PREFIX=/usr ..
make %{?_smp_mflags}

popd
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
DESTDIR=%{buildroot} make -C rpmbuilddir-%{_arch} install
mkdir -p %{_bindir}
# << install pre

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_bindir}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/*/apps/%{name}.png
# >> files
# << files
